### ISSUE TITLE
求助：export OPENAI_API_KEY="your_api_key_here" error

### ISSUE THREAD

**Issue by tiamojames** [OpenBMB/AgentVerse#1]
我在anaconda prompt 上使用set OPENAI_API_KEY="your_api_key_here" 进行导入，之后运行main.py时报错提示没有api key，
error message: 
Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or 
pass  `openai_api_key` as a named parameter. (type=value_error)

**Comment by chenweize1998** [comment]
你应该使用`export`来设置环境变量：
```bash
export OPENAI_API_KEY="your_api_key_here"
python ...
```

**Comment by tiamojames** [comment]
> 你应该使用`export`来设置环境变量：
> 
> ```shell
> export OPENAI_API_KEY="your_api_key_here"
> python ...
> ```

可是在annconda中使用export OPENAI_API_KEY="your_api_key_here" 导入提示错误：'export' 不是内部或外部命令，也不是可运行的程序或批处理文件。 我在网上搜索说windows需要用set

**Comment by chenweize1998** [comment]
我们没有在windows上测试过，对于windows环境也不是特别熟悉，但作为一个workaround你可以尝试一下在main.py的开头用
```python
import os
os.environ["OPENAI_API_KEY"] = "your_api_key_here"
```
看看能否成功

**Comment by tiamojames** [comment]
> 

很遗憾，还是相同的问题。我想询问在你们工程文件中是否可以直接将其中的api_key换成个人的api然后运行，如果可以，能否告知我具体应该修改哪些文件程序中的api_key.

**Comment by chenweize1998** [comment]
更换为个人api比较麻烦，可能需要自定义agent。还有一个加入OPENAI_API_KEY可以尝试的方法是直接修改系统的环境变量，参考[微软官方文档](https://support.microsoft.com/zh-cn/topic/%E5%A6%82%E4%BD%95%E7%AE%A1%E7%90%86-windows-xp-%E4%B8%AD%E7%9A%84%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F-5bf6725b-655e-151c-0b55-9a8c9c7f747d)

**Comment by Dr-Left** [comment]
From my perspective, you may try setting the environment variable manually by right clicking "This PC" -> Properties -> advanced system settings.

**Comment by Dr-Left** [comment]
> 更换为个人api比较麻烦，可能需要自定义agent。还有一个加入OPENAI_API_KEY可以尝试的方法是直接修改系统的环境变量，参考[微软官方文档](https://support.microsoft.com/zh-cn/topic/%E5%A6%82%E4%BD%95%E7%AE%A1%E7%90%86-windows-xp-%E4%B8%AD%E7%9A%84%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F-5bf6725b-655e-151c-0b55-9a8c9c7f747d)

Yep

**Comment by chenweize1998** [comment]
这个或许是langchain的一个问题。你可以尝试将https://github.com/OpenBMB/AgentVerse/blob/9660b3b34a4021c3576f05c8f15eff46544ff3a0/agentverse/agents/agent.py#L32-L34
中的openai.proxy直接设置为你的代理服务器地址。我们在linux上测试时，因为代理都存在http_proxy或HTTP_PROXY环境变量中，所以我们从其中读取。windows情况可能有所不同。
