### ISSUE TITLE
ModuleNotFoundError: No module named 'bmtools.agent'

### ISSUE THREAD

**Issue by KeysaYoung** [OpenBMB/AgentVerse#10]
你好，安装最新版本的AgentVerse和BMTools之后，出现了这个ModuleNotFoundError: No module named 'bmtools.agent'。我看了下bmtools package里面好像也没这个定义

**Comment by KeysaYoung** [comment]
貌似是faiss这个包和pycharm编译的问题，比较玄学的解决了。
但是每次调用API之后就会出现一个报错，虽然不影响运行，但感觉是哪儿有一个小问题：

05/26/2023 09:54:05 - INFO - root - Police: "Suspects, I want to remind you that if both of you remain silent, you will each get one year in prison. However, if you both choose to betray each other and testify against one another, you will both receive five years in prison. So, think carefully before you make your decision."
05/26/2023 09:54:05 - INFO - httpx - HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
05/26/2023 09:54:05 - INFO - httpx - HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001A4425585E0>
Traceback (most recent call last):
  File "C:\Users\anaconda3\envs\AgentVerse\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\anaconda3\envs\AgentVerse\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\anaconda3\envs\AgentVerse\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Users\anaconda3\envs\AgentVerse\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
05/26/2023 09:54:05 - INFO - httpx - HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"

**Comment by dexhunter** [comment]
+1 

> 貌似是faiss这个包和pycharm编译的问题，比较玄学的解决了。

想问问是怎么解决的

**Comment by dexhunter** [comment]
> 想问问是怎么解决的

## 解决方法

1. (optional)新建python=3.8的virtual env
2. 卸载已经安装的BMTools
3. 去[BMTools Github主页](https://github.com/OpenBMB/BMTools)安装最新版本
```
git clone git@github.com:OpenBMB/BMTools.git
cd BMTools
pip install --upgrade pip
pip install -r requirements.txt
python setup.py develop
```
4. 启用AgentVerse

**Comment by chenweize1998** [comment]
Closing this issue since it is resolved
