### ISSUE TITLE
requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by luocacy** [OpenBMB/AgentVerse#106]
命令：python main_simulation_cli.py --task simulation/math_problem_2players_tools
报错：requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8079): Max retries exceeded with url: /tools/wolframalpha/.well-known/ai-plugin.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000
02029FF1E650>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

**Comment by chenweize1998** [comment]
这个case需要安装bmtools，请按照[readme](https://github.com/OpenBMB/AgentVerse?tab=readme-ov-file#gui-example)进行安装
