### ISSUE TITLE
开箱即用版本的 Agent Verse

### ISSUE THREAD

**Issue by soulteary** [OpenBMB/AgentVerse#109]
项目维护者你好👋

这个项目很有趣，但是初始化的时候，容易遇到这样或者那样的问题，包括 OpenCV 依赖、可选的 BMB 依赖等等。

或许，可以考虑折腾一个 Docker 容器或者基础的配置，来让大家开箱即用？

我提交了一个 PR https://github.com/OpenBMB/AgentVerse/pull/107 ，希望有帮助。

**Comment by chenweize1998** [comment]
看起来很不错！非常感谢你的贡献！我这几天有空会review一下
