### ISSUE TITLE
ModuleNotFoundError: No module named 'agentverse'

### ISSUE THREAD

**Issue by znzjugod** [OpenBMB/AgentVerse#113]
我拉取最新的代码，尝试运行囚徒困境的demo，执行python agentverse_command/main_simulation_gui.py --task simulation/prisoner_dilemma后报错：
![image](https://github.com/OpenBMB/AgentVerse/assets/106044623/e7a35919-d961-46bb-aa3a-5a6a84a9c720)

**Comment by chenweize1998** [comment]
你需要在AgentVerse仓库根目录下运行`pip install -e .`
