### ISSUE TITLE
How to define your own task

### ISSUE THREAD

**Issue by anchicken** [OpenBMB/AgentVerse#114]
If i want to define my own simulation task and don't need dataset. Is this all I need to design my own YAML file in the tasks folder and run it?

**Comment by chenweize1998** [comment]
Right. You can create a custom YAML file based on any existing one in `agentverse/tasks/simulation`. Then, execute your code using `python agentverse_command/main_simulation_cli.py --task your_task_name`. If you run into any issues, feel free to reach out for assistance.

**Comment by anchicken** [comment]
OK, I understand. thanks so much.
