### ISSUE TITLE
更改本地端口的文件在哪里

### ISSUE THREAD

**Issue by GJZ0819** [OpenBMB/AgentVerse#116]
使用GUI执行agentverse-simulation-gui --task simulation/nlp_classroom_9players时，默认使用的本地端口并不是我需要的，我想更改本地端口为6006，但并没有找到端口的定义文件

**Comment by chenweize1998** [comment]
尝试在这个lauch里加上你的端口`server_port=xxx`https://github.com/OpenBMB/AgentVerse/blob/5fb1f7713988c0ef71c1a8a455d7a74d821fd7cb/agentverse/gui.py#L564
