### ISSUE TITLE
UserWarning: You are trying to use a chat model. This way of initializing it is no longer supported. 

### ISSUE THREAD

**Issue by logicbai** [OpenBMB/AgentVerse#14]
langchain/llms/openai.py:169: UserWarning: You are trying to use a chat model. This way of initializing it is no longer supported. Instead, please use: `from langchain.chat_models import ChatOpenAI`

**Comment by chenweize1998** [comment]
The warning comes from BMTools. I tried the latest version of BMTools and the warning seems to be have resolved. If it still exists, you can report it to BMTools.
