### ISSUE TITLE
npm install ERROR in Pokemon

### ISSUE THREAD

**Issue by KeysaYoung** [OpenBMB/AgentVerse#17]
在第二个终端输入npm install之后报错。具体如下：

在第一个终端显示：
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:\\AgentVerse\\ui\\node_modules\\.staging\\eventemitter3-1e3b8f15\\umd'

在第二个终端显示：
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules\rollup\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN node-fetch@2.6.11 requires a peer of encoding@^0.1.0 but none was installed.
npm WARN vite-plugin-static-copy@0.15.0 requires a peer of vite@^3.0.0 || ^4.0.0 but none was installed.
npm ERR! Windows_NT 10.0.19044
npm ERR! argv "C:\\Users\\anaconda3\\envs\\agentverse\\Library\\bin\\node.exe" "C:\\Users\\anaconda3\\envs\\agentverse\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! path C:\AgentVerse\ui\node_modules\.staging\@types\estree-a9be2c14\package.json
npm ERR! code ENOTDIR
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! ENOENT: no such file or directory, open 'C:\AgentVerse\ui\node_modules\.staging\@types\estree-a9be2c14\package.json'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\AgentVerse\ui\npm-debug.log

输入npm -v能正常显示版本号，感觉不像是安装包的原因。

**Comment by KeysaYoung** [comment]
感谢！我重新安装了最新版的node@20.2.0和npm@9.6.7，没有出现之前的npm install error。但是仍然没有成功运行Pokemon。

运行npm run watch之后显示如下：

[!] RollupError: Could not resolve "./cover/Factory.js" from "src/phaser3-rex-plugins/templates/ui/ui-plugin.js"
src/phaser3-rex-plugins/templates/ui/ui-plugin.js
    at error (C:\AgentVerse\ui\node_modules\rollup\dist\shared\rollup.js:279:30)
    at ModuleLoader.handleInvalidResolvedId (C:\AgentVerse\ui\node_modules\rollup\dist\shared\rollup.js:24433:24)
    at C:\AgentVerse\ui\node_modules\rollup\dist\shared\rollup.js:24395:26

[2023-06-06 21:03:21] waiting for changes...

请问这个可能是哪方面的原因呢？

**Comment by KeysaYoung** [comment]
感谢！现在可以成功加载界面了~

另外想请问一下，经常会遇到这两种问题： 

ERROR - root - Rate limit reached for default-gpt-3.5-turbo in organization org-EfoPZs1crcYxxwPEFSqxXTRA on requests per min

ERROR - root - Maxie failed to generate valid response.

1）在哪里可以设置retrying的上限呢？也就是openai query重新尝试的次数。因为网络不稳定的话可能会重新连接很多次。
2）或许可以加上一种设置：出现invalid action之后，这次query就被忽略，本次对话on hold，然后重新连接，而不会直接进入到下一个conversation 。

**Comment by chenweize1998** [comment]
You can simply add a `max_retry` property in each agent's config. For example
```yaml
agents:
  - agent_type: conversation
    name: May
    max_retry: 10
```

And thanks for you suggestion in (2)! We will consider it in future.

**Comment by KeysaYoung** [comment]
明白了，非常感谢！
