### ISSUE TITLE
请问可以使用gpt-3.5-turbo模型吗？

### ISSUE THREAD

**Issue by SpecterHi** [OpenBMB/AgentVerse#2]
您好！
我注意到目前的demo中，每个task的config.yaml中的llm_type是text-davinci-003，我尝试直接将其替换为gpt-3.5-turbo，程序会报错无法正常运行。

请问正确的做法是怎样，或者后续会有模型选择方面的改进和说明吗？

非常感谢！

**Comment by chenweize1998** [comment]
During testing, we found that gpt-3.5-turbo has a weaker understanding of prompts compared to text-davinci-003. When using gpt-3.5-turbo, there are frequent instances of it violating the specified rules in the prompt. Therefore, in the current version, for a better user experience, we are temporarily only considering text-davinci-003. However, we will soon modify the code to support gpt-3.5-turbo as well.

**Comment by KeysaYoung** [comment]
请问现在的版本，需要修改哪个部分，才能支持got-3.5-turbo呢？

**Comment by chenweize1998** [comment]
> 请问现在的版本，需要修改哪个部分，才能支持gpt-3.5-turbo呢？

@KeysaYoung If you want to use gpt-3.5-turbo for now, you can take a look at `remove_langchain` branch. In this branch, we remove the dependency on langchain and support using gpt-3.5-turbo. The configuration files have been also slightly modified. You can take a look at the task `nlp_classroom_3players_nolc` in /tasks/ in that branch (and other tasks with `nolc` suffix). Replacing all the occurrence of "gpt-4" with "gpt-3.5-turbo" in the config, you can then use "gpt-3.5-turbo". The branch is now currently under development, we have not tested it extensively. However, the code should be good for scenarios without tool. 

If you're not in a hurry to use it, you can wait a few days for us to formally release a version.

**Comment by chenweize1998** [comment]
gpt-3.5-turbo is now supported. closing the issue.
