### ISSUE TITLE
求助：ERROR - root - Error communicating with OpenAI

### ISSUE THREAD

**Issue by zmgy107** [OpenBMB/AgentVerse#20]
在我运行main.py时，遇到如下报错：
![2023-07-07T16_18_44](https://github.com/OpenBMB/AgentVerse/assets/122243664/ad350ab3-2f89-43b1-9dcc-ff74fca9ae49)
![2023-07-07T16_19_01](https://github.com/OpenBMB/AgentVerse/assets/122243664/4c65cb82-7543-4ad2-a62c-9f292b96f17b)

我是用的梯子开了全局模式，并且测试了我的api是可以正常使用的。请问我应该怎样解决这个问题呢？

**Comment by chanchimin** [comment]
If you are using clash, you can try to add theses lines at the beginning of main.py .

```python
import os

os.environ["http_proxy"] = "http://127.0.0.1:7890"
os.environ["https_proxy"] = "http://127.0.0.1:7890"
os.environ["all_proxy"] = "socks5://127.0.0.1:7890"
```

**Comment by zmgy107** [comment]
> If you are using clash, you can try to add theses lines at the beginning of main.py .
> 
> ```python
> import os
> 
> os.environ["http_proxy"] = "http://127.0.0.1:7890"
> os.environ["https_proxy"] = "http://127.0.0.1:7890"
> os.environ["all_proxy"] = "socks5://127.0.0.1:7890"
> ```

Acatully,I tried prefixing the code with this passage, but the problem was not solved.

**Comment by chanchimin** [comment]
OK, I understand, but just a double check, please make sure these lines are added before the agentverse package is imported. It should be organized strictly in the following order.
`
import os

os.environ["http_proxy"] = "http://127.0.0.1:7890"
os.environ["https_proxy"] = "http://127.0.0.1:7890"
os.environ["all_proxy"] = "socks5://127.0.0.1:7890"

from agentverse.agentverse import AgentVerse
`
If it still does not work, then you might check if the proxy is correctly set by running curl www.google.com in the command line first.

**Comment by chanchimin** [comment]
OK, I understand, but just a double check, please make sure these lines are added before the agentverse package is imported. It should be organized strictly in the following order.
```
import os

os.environ["http_proxy"] = "http://127.0.0.1:7890/"
os.environ["https_proxy"] = "http://127.0.0.1:7890/"
os.environ["all_proxy"] = "socks5://127.0.0.1:7890"

from agentverse.agentverse import AgentVerse
```
If it still does not work, then you might check if the proxy is correctly set by running curl [www.google.com](http://www.google.com/) in the command line first.

**Comment by chanchimin** [comment]
> > If you are using clash, you can try to add theses lines at the beginning of main.py .
> > ```python
> > import os
> > 
> > os.environ["http_proxy"] = "http://127.0.0.1:7890"
> > os.environ["https_proxy"] = "http://127.0.0.1:7890"
> > os.environ["all_proxy"] = "socks5://127.0.0.1:7890"
> > ```
> 
> Acatully,I tried prefixing the code with main.py, but the problem was not solved.

OK, I understand, but just a double check, please make sure these lines are added before the agentverse package is imported. It should be organized strictly in the following order.

```
import os

os.environ["http_proxy"] = "http://127.0.0.1:7890/"
os.environ["https_proxy"] = "http://127.0.0.1:7890/"
os.environ["all_proxy"] = "socks5://127.0.0.1:7890"

from agentverse.agentverse import AgentVerse

```
If it still does not work, then you might check if the proxy is correctly set by running curl [www.google.com](http://www.google.com/) in the command line first.

**Comment by chanchimin** [comment]
> > If you are using clash, you can try to add theses lines at the beginning of main.py .
> > ```python
> > import os
> > 
> > os.environ["http_proxy"] = "http://127.0.0.1:7890"
> > os.environ["https_proxy"] = "http://127.0.0.1:7890"
> > os.environ["all_proxy"] = "socks5://127.0.0.1:7890"
> > ```
> 
> Acatully,I tried prefixing the code with main.py, but the problem was not solved.

OK, I understand, but just a double check, please make sure these lines are added before the agentverse package is imported. It should be organized strictly in the following order.

```
import os

os.environ["http_proxy"] = "http://127.0.0.1:7890"
os.environ["https_proxy"] = "http://127.0.0.1:7890"
os.environ["all_proxy"] = "socks5://127.0.0.1:7890"

from agentverse.agentverse import AgentVerse

```
If it still does not work, then you might check if the proxy is correctly set by running curl [www.google.com](http://www.google.com/) in the command line first.
Remember that you need to run 
```
export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890
```
before curl in the command line.

**Comment by tianyalangzi** [comment]
I have the same problem with macos setting up http_proxy as mentioned above and still have the same error, how do I fix this error?

**Comment by chanchimin** [comment]
> I have the same problem with macos setting up http_proxy as described above and still have the same error, how do I fix this error? @chanchimin

The issue seems to be related to a network connection problem rather than an AgentVerse problem. Before proceeding, it's advisable to test your connection to www.google.com to ensure its functionality. Additionally, you may want to verify if your VPN port matches your http_proxy settings.
