### ISSUE TITLE
Unable to open on webpage/webpage display exception

### ISSUE THREAD

**Issue by yaosting** [OpenBMB/AgentVerse#23]
I completed the installation according to readme and configured the key, but when I tried running python3 main_demo.py --task nlp_classroom_9players 

I cannot get the expected results on the webpage, and when I run other main_ During demo, there are still similar issues

<img width="935" alt="image" src="https://github.com/OpenBMB/AgentVerse/assets/39480659/277f8ae4-690f-43ca-80f7-d4ef9322f9b0">
<img width="789" alt="image" src="https://github.com/OpenBMB/AgentVerse/assets/39480659/0aa35e81-d34e-4aaf-a07b-52f105e426bf">

**Comment by yushengsu-thu** [comment]
@yaosting 
I run the same case with the latest version but I didn't encounter this problem.
<img width="724" alt="Screen Shot 2023-08-03 at 12 06 07 AM" src="https://github.com/OpenBMB/AgentVerse/assets/11704492/e95f84e1-14f7-41ca-b976-a8ffd926bfa5">

 Did you run this case on Windows, MacOs, or Linux?

**Comment by chenweize1998** [comment]
Closing for lack of feedback. Feel free to re-open it.
