### ISSUE TITLE
求助！这个是什么问题ErrorExpecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Summercuisine** [OpenBMB/AgentVerse#26]
08/12/2023 11:42:52 - INFO - httpx - HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 502 Bad Gateway"
08/12/2023 11:42:52 - INFO - httpx - HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 502 Bad Gateway"
08/12/2023 11:43:34 - INFO - httpx - HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 502 Bad Gateway"
08/12/2023 11:43:34 - INFO - httpx - HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 502 Bad Gateway"

**Comment by chenweize1998** [comment]
What command did you run?

**Comment by chenweize1998** [comment]
Closing for lack of feedback. Feel free to re-open it.
