### ISSUE TITLE
Error communicating with OpenAI

### ISSUE THREAD

**Issue by zhuxiaosheng** [OpenBMB/AgentVerse#28]
最新生成的KEY，游戏画面能进入，但是提示Error communicating with OpenAI

![截屏2023-08-13 11 52 25](https://github.com/OpenBMB/AgentVerse/assets/2718879/a82dfe45-d4f4-4088-b281-be1382b12864)

**Comment by chenweize1998** [comment]
You can try the solution provided in https://github.com/OpenBMB/AgentVerse/issues/20#issuecomment-1636659010. Change the port `7890` mentioned in the answer to the port listened by your tunnel app. 7890 is the default port listened by Clash.
