### ISSUE TITLE
如果想新建一个场景并运行，请问这个报错如何解决

### ISSUE THREAD

**Issue by fjaijf** [OpenBMB/AgentVerse#34]
pydantic.error_wrappers.ValidationError: 1 validation error for ConversationAgent
prompt_template
  field required (type=value_error.missing)

**Comment by chenweize1998** [comment]
You need to pass `prompt_template` to your agent in your `config.yaml`. See https://github.com/OpenBMB/AgentVerse/blob/08a06d37937ed24c3e1b1797aee89ffa0f322092/agentverse/tasks/nlp_classroom_3players/config.yaml#L2-L10 and https://github.com/OpenBMB/AgentVerse/blob/08a06d37937ed24c3e1b1797aee89ffa0f322092/agentverse/tasks/nlp_classroom_3players/config.yaml#L37
