### ISSUE TITLE
运行demo卡死

### ISSUE THREAD

**Issue by Angelo3357** [OpenBMB/AgentVerse#39]
<img width="1585" alt="截屏2023-09-17 20 34 50" src="https://github.com/OpenBMB/AgentVerse/assets/61720852/30b13dca-fcb8-4382-bbb8-32ce1304a44a">

**Comment by chenweize1998** [comment]
Could you show the console output? Also, I noticed issue #38  that you've suggested, you can first attempt to address that issue and see if it resolves the problem.

**Comment by chenweize1998** [comment]
Closing the issue for no feedback.
