### ISSUE TITLE
multiple agents acting at the same time

### ISSUE THREAD

**Issue by lzw-lzw** [OpenBMB/AgentVerse#42]
Thank you for your excellent work. I would like to know whether the current framework supports multiple agents acting at the same time or only supports one agent acting at a time.

**Comment by chenweize1998** [comment]
Take a look at https://github.com/OpenBMB/AgentVerse/blob/main/agentverse/environments/rules/order/concurrent.py and see whether it suits your need. When you configure the `order` to `concurrent`, all the agents will act at the same time at each iteration.

**Comment by lzw-lzw** [comment]
Thanks a lot!
