### ISSUE TITLE
keep saying no connect

### ISSUE THREAD

**Issue by silvery-feather** [OpenBMB/AgentVerse#43]
in pycharm terminal it just keep saying all of this 

09/25/2023 19:17:33 - WARNING - root - Retrying...
09/25/2023 19:17:56 - ERROR - root - Error communicating with OpenAI
09/25/2023 19:17:56 - WARNING - root - Retrying...
09/25/2023 19:18:27 - ERROR - root - Error communicating with OpenAI
09/25/2023 19:18:27 - WARNING - root - Retrying...
09/25/2023 19:18:27 - ERROR - root - Teaching Assistant Gamma failed to generate valid response.
09/25/2023 19:18:27 - INFO - root - Teaching Assistant Gamma:
09/25/2023 19:18:51 - ERROR - root - Error communicating with OpenAI
09/25/2023 19:18:51 - WARNING - root - Retrying...

**Comment by chenweize1998** [comment]
What's your OS system? And are you using any VPN?

**Comment by silvery-feather** [comment]
window10 ，yeah，i use vpn,but I already use a global proxy，is this the problem?

**Comment by silvery-feather** [comment]
![MB _(XS2GZMFP1@K2M%@HC2](https://github.com/OpenBMB/AgentVerse/assets/75378944/22096198-1e6b-4683-8bcc-b3cab068bfce)
![@~B$O 3)5YF4L9BD8TP($TY](https://github.com/OpenBMB/AgentVerse/assets/75378944/d1aa940a-9867-4afa-a3d9-197b6fa7917d)

**Comment by silvery-feather** [comment]
thats what it look like , thanks for the reply

**Comment by chenweize1998** [comment]
If you are using clash, you can try this solution https://github.com/OpenBMB/AgentVerse/issues/20#issuecomment-1636659010. If not, you should replace the `7890` with the proxy port listened by your VPN.

**Comment by silvery-feather** [comment]
although i use the v2ray ,i still try the #20 , it does not work , and i cant go to 127.0.0.1 now

requests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=7890): Max retries exceeded with url: http://127.0.0.1:7860/startup-events (Caused by ProxyError('Cannot c
onnect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000207F3FC1E40>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒
绝，无法连接。')))

**Comment by silvery-feather** [comment]
oh,it seem work,but there is anthor mistake

ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.

what should i do with it

**Comment by chenweize1998** [comment]
I haven't seen this error before. Try add `share=True` in `launch` at https://github.com/OpenBMB/AgentVerse/blob/06e97ef69de4c136a9140223903982442b13084f/agentverse/demo.py#L486

**Comment by silvery-feather** [comment]
the problem i just say , i have solve it myself
although i use the v2ray ,i still try the #20 , it does not work , and i cant go to 127.0.0.1 now
what should i do now,should i use the clash?

**Comment by silvery-feather** [comment]
oh,i just try clash,it have some changes,but it still have problem.what should i do now

![03](https://github.com/OpenBMB/AgentVerse/assets/75378944/703c51a0-8f5d-4440-bd42-4e984144debb)

**Comment by chenweize1998** [comment]
I currently don't have access to a Windows machine to verify this issue. However, you might want to check out [this related thread](https://github.com/Fndroid/clash_for_windows_pkg/issues/1470). PyCharm might require additional configuration to work properly with the proxy provided by Clash.

**Comment by silvery-feather** [comment]
so sad,it just doesnt work , it still like my first pictrue now,just doesnt work

**Comment by silvery-feather** [comment]
i mean i can use the terminal in pycharm to go to [www.](https://www.google.com/)
just use "curl [www.google.com](http://www.google.com/)",it works , but when i use agentverse it just like yesterday , just 

09/26/2023 17:03:34 - ERROR - root - Error communicating with OpenAI
09/26/2023 17:03:34 - WARNING - root - Retrying...
09/26/2023 17:04:00 - ERROR - root - Error communicating with OpenAI
09/26/2023 17:04:00 - WARNING - root - Retrying...
09/26/2023 17:04:16 - ERROR - root - Error communicating with OpenAI
09/26/2023 17:04:16 - WARNING - root - Retrying...
09/26/2023 17:04:42 - ERROR - root - Error communicating with OpenAI
09/26/2023 17:04:42 - WARNING - root - Retrying...
09/26/2023 17:04:58 - ERROR - root - Error communicating with OpenAI
09/26/2023 17:04:58 - WARNING - root - Retrying...
09/26/2023 17:04:58 - ERROR - root - Police failed to generate valid response.
09/26/2023 17:04:58 - INFO - root - Police:
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
09/26/2023 17:05:24 - ERROR - root - Error communicating with OpenAI
09/26/2023 17:05:24 - WARNING - root - Retrying...
09/26/2023 17:05:24 - ERROR - root - Police failed to generate valid response.
09/26/2023 17:05:24 - INFO - root - Police:
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
09/26/2023 17:06:06 - ERROR - root - Error communicating with OpenAI
09/26/2023 17:06:06 - WARNING - root - Retrying...

**Comment by chenweize1998** [comment]
The core issue appears to be that the `openai` package employs `aiohttp` for asynchronous requests. By default, `aiohttp` doesn't utilize the system proxy. Only when you specify the `openai.proxy` variable, it forwards the proxy to `aiohttp`, allowing it to use your proxy.

We've explicitly defined the proxy here: https://github.com/OpenBMB/AgentVerse/blob/4ed4783f248875bc9e6efeda33482cc2d460f139/agentverse/llms/openai.py#L24-L26
However, this approach seems not to be effective on Windows. Admittedly, my expertise with Windows and Pycharm is limited, so I cannot provide a definitive solution. Nevertheless, consider these suggestions:

1. If you've already configured Pycharm's proxy, delete the `os.environ['...']='xxx'` part.
2. Remove the `openai.proxy` setting in the above code.

For testing, here's a minimum snippet that directly calls the openai async interface. **If this script executes without issues in your terminal, it's likely AgentVerse will run as well:**

```python3
import openai
import asyncio

openai.proxy = "http://127.0.0.1:7890"

async def create_chat_completion():
    chat_completion_resp = await openai.ChatCompletion.acreate(model="gpt-3.5-turbo", messages=[{"role": "user", "content": "Hello world"}])
    return chat_completion_resp

if __name__ == '__main__':
    response = asyncio.run(create_chat_completion())
    print(response)
```

On Mac and Linux, by adding `openai.proxy = "http://127.0.0.1:7890"` after importing `openai`, the code will call the openai's async interface successfully. But I'm not sure what will be the case on Windows.

**Comment by silvery-feather** [comment]
thanks for you patient solving my problem,but it still doesnt work 
even the code you give me which is used to test still have mistake, can you solve it?
![D)XOA6($%AS~0PYCGBLE6OR](https://github.com/OpenBMB/AgentVerse/assets/75378944/f64de317-fc3a-4e5a-9200-3b5185d24f92)

**Comment by chenweize1998** [comment]
The code I gave is to test whether you can succefully call the openai's async interface in your terminal. If the given code fails, it means that your terminal does not correctly configure the openai's proxy.  Have you tried to directly access the openai interface in your terminal? 
```bash
curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "gpt-3.5-turbo",
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant."
      },
      {
        "role": "user",
        "content": "Hello!"
      }
    ]
  }'

```
If it fails, then it might be the problem of your proxy server.

**Comment by silvery-feather** [comment]
it seems it have something back , and i try openbmb/chatdev yesterday,i success.
![06](https://github.com/OpenBMB/AgentVerse/assets/75378944/e0d3bd1b-d5c4-4732-970a-6d676e2ca3f8)

**Comment by chenweize1998** [comment]
ChatDev does not utilize OpenAI's asynchronous interface, thus there's no need to address the proxy issue within `aiohttp`, which is only used in async interface. Have you considered launching AgentVerse using the `cmd` terminal? Does the provided code also encounter issues when executed in `cmd`?

```python3
import openai
import asyncio

openai.proxy = "http://127.0.0.1:7890"

async def create_chat_completion():
    chat_completion_resp = await openai.ChatCompletion.acreate(model="gpt-3.5-turbo", messages=[{"role": "user", "content": "Hello world"}])
    return chat_completion_resp

if __name__ == '__main__':
    response = asyncio.run(create_chat_completion())
    print(response)
```

**Comment by chenweize1998** [comment]
I just found a potential solution within OpenAI's repository at https://github.com/openai/openai-python/issues/278#issuecomment-1473357978. As previously mentioned, the issue originates from `aiohttp` not being able to navigate through the system proxy. By setting `trust_env=True`, it's possible that `aiohttp` will be able to utilize the system proxy.

**Comment by chenweize1998** [comment]
You can take a try on the current version of code. It should be fixed. For now, I will close the issue until there is further feedback.
