### ISSUE TITLE
 Error communicating with OpenAI

### ISSUE THREAD

**Issue by yafon-max** [OpenBMB/AgentVerse#45]
10/01/2023 20:28:31 - ERROR - root - Error communicating with OpenAI
10/01/2023 20:28:31 - WARNING - root - Retrying...
10/01/2023 20:29:48 - ERROR - root - Error communicating with OpenAI
10/01/2023 20:29:48 - WARNING - root - Retrying...

**Comment by chenweize1998** [comment]
1. Make sure your terminal can acess the openai's API. A testing script may be 
```bash
curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "gpt-3.5-turbo",
    "messages": [
      {
        "role": "user",
        "content": "Hello!"
      }
    ]
  }'
```
2. If you successfully obtain the returned response, then try to change the code at https://github.com/OpenBMB/AgentVerse/blob/4ed4783f248875bc9e6efeda33482cc2d460f139/agentverse/llms/openai.py#L121-L123
into
```python3
async with ClientSession(trust_env=True) as session:
    openai.aiosession.set(session)
    response = await openai.ChatCompletion.acreate( 
        messages=messages, **self.args.dict() 
    )
```
and run the code to see whether it works

**Comment by yafon-max** [comment]
> 1. Make sure your terminal can acess the openai's API. A testing script may be
> 
> ```shell
> curl https://api.openai.com/v1/chat/completions \
>   -H "Content-Type: application/json" \
>   -H "Authorization: Bearer $OPENAI_API_KEY" \
>   -d '{
>     "model": "gpt-3.5-turbo",
>     "messages": [
>       {
>         "role": "user",
>         "content": "Hello!"
>       }
>     ]
>   }'
> ```
> 
> 2. If you successfully obtain the returned response, then try to change the code at https://github.com/OpenBMB/AgentVerse/blob/4ed4783f248875bc9e6efeda33482cc2d460f139/agentverse/llms/openai.py#L121-L123
>    
>    into
> 
> ```python
> async with ClientSession(trust_env=True) as session:
>     openai.aiosession.set(session)
>     response = await openai.ChatCompletion.acreate( 
>         messages=messages, **self.args.dict() 
>     )
> ```
> 
> and run the code to see whether it works

this is the result ：curl: (28) Failed to connect to api.openai.com port 443 after 75215 ms: Couldn't connect to server

**Comment by yafon-max** [comment]
我发现，我通过在pycharm跑py文件测试openai可以访问：
`import requests
YOUR_OPENAI_API_KEY = 'xxxxx'
url = 'https://api.openai.com/v1/chat/completions'
headers = {
    'Content-Type': 'application/json',
    'Authorization': 'Bearer ' + YOUR_OPENAI_API_KEY
}
data = {
    'model': 'gpt-3.5-turbo',
    'messages': [
        {
            'role': 'user',
            'content': 'Hello!'
        }
    ]
}
response = requests.post(url, headers=headers, json=data)
json_response = response.json()
print(json_response)`
但是我将该代码复制到制定位置，
`async with ClientSession(trust_env=True) as session:
    openai.aiosession.set(session)
    response = await openai.ChatCompletion.acreate( 
        messages=messages, **self.args.dict() 
    )`
就出现了这个问题：
`10/03/2023 16:08:39 - ERROR - root - name 'ClientSession' is not defined
10/03/2023 16:08:39 - WARNING - root - Retrying...
10/03/2023 16:08:39 - ERROR - root - name 'ClientSession' is not defined
10/03/2023 16:08:39 - WARNING - root - Retrying...
10/03/2023 16:08:39 - ERROR - root - Student Emma failed to generate valid response.
10/03/2023 16:08:39 - INFO - root - Professor Michael: 
10/03/2023 16:08:39 - ERROR - root - name 'ClientSession' is not defined
`

**Comment by chenweize1998** [comment]
Apologies for the delayed response; I was away on vacation. Now, let's address your concerns:

1. It appears that the curl command has encountered an issue, suggesting that your proxy configuration might be incorrect. To resolve this, consider switching to a different proxy server—ensuring that the server's IP is not located in China or Hong Kong. It's crucial to establish a properly functioning proxy server before we can proceed further.

2. The error stating that 'name 'ClientSession' is not defined' can be resolved by adding an import statement at the beginning of your file. You can resolve this issue by including the following line: `from aiohttp import ClientSession`.

**Comment by chenweize1998** [comment]
Closing the issue because the problem has been solved via email.
