### ISSUE TITLE
Bug: Miss 'get_embedding' in 'agentverse.llms.openai' 

### ISSUE THREAD

**Issue by JetSquirrel** [OpenBMB/AgentVerse#46]
I try to run demo:
```shell
$ python3 main_demo.py --task db_diag
```
But have a bug
```shell
$ ImportError: cannot import name 'get_embedding' from 'agentverse.llms.openai'
```
I comfirmed in commit [c89a6c5](https://github.com/OpenBMB/AgentVerse/commit/c89a6c5c401911df59b19c912b9ab8a8d94b9723). It's look like "get_embedding" function wash deleted.
![image](https://github.com/OpenBMB/AgentVerse/assets/20291255/66d2ff89-2974-4915-8168-d8f8f418f94a)

please help to fix this problem.

**Comment by chenweize1998** [comment]
I have fixed it, please try again. But we're in the midst of refactoring our code, and as a result, we haven't tested the demo under the current code. For a more stable version, you can see the `release-1.0` branch.

**Comment by JetSquirrel** [comment]
Thanks. I try to run but still have some problem. I plan use `release-1.0` still `release-2.0` to stable.

I would like to contribute code to this project, can you provider some good-first-issue ? Thank you very mush.

**Comment by chenweize1998** [comment]
We are happy that you are willing to contribute! Could you please provide details about the problem? I will try to pinpoint the codes that need modification.

**Comment by JetSquirrel** [comment]
I fixed this problem it in PR #48, 

and still have some problem when run `python main_simulation_gui.py --task db_diag`:
![image](https://github.com/OpenBMB/AgentVerse/assets/20291255/637e2bd7-a724-4ba2-bd51-986d0802d040)

I don't know how to fix it, can you help me?

**Comment by chenweize1998** [comment]
We mistakenly commented out the support of BMTools in simulation environments. We have added it back. Please check again.

**Comment by JetSquirrel** [comment]
Great! Thank you!
