### ISSUE TITLE
[Request] Adding Minecraft Example

### ISSUE THREAD

**Issue by RavenLeeANU** [OpenBMB/AgentVerse#47]
Hi Team!

Thanks for your contribution! I wonder if you can add minecraft example mentioned in the paper to this repo, so that we can observe the volunteer behaviors. That is a lot of fun.

Have a great time!

**Comment by chenweize1998** [comment]
Absolutely! We'll release it in the next few days. It'll be based on the prior version of AgentVerse (release-1.0 branch). We currently do not have time to migrate it to the latest version. I'm considering creating a new branch specifically for the Minecraft environment to ensure reproducibility. We appreciate your patience and will release it promptly. Stay tuned!

**Comment by chenweize1998** [comment]
I just uploaded our codebase for Minecraft example in the [`minecraft` branch](https://github.com/OpenBMB/AgentVerse/tree/minecraft), you can take a look now!
