### ISSUE TITLE
建议把gradio的启动server name作为配置暴露出来，不然现在只能127.0.0.1本地体验，不方便

### ISSUE THREAD

**Issue by weibinke** [OpenBMB/AgentVerse#61]

**Comment by chenweize1998** [comment]
Thanks for the advice. Before we modify it, you can change the following line
https://github.com/OpenBMB/AgentVerse/blob/88744f1089f689bcebb6c9aaa4c9fcc9f1aee549/agentverse/gui.py#L505
to 
```python3
demo.queue(concurrency_count=5, max_size=20).launch(server_name="0.0.0.0")
```

**Comment by JetSquirrel** [comment]
@chenweize1998  Can you assigne this issue to me?

**Comment by chenweize1998** [comment]
> @chenweize1998 Can you assigne this issue to me?

Sure! That would be awesome if you can help!

**Comment by JetSquirrel** [comment]
please review #63, thank you!
