### ISSUE TITLE
How to launch the Text Evaluation example?

### ISSUE THREAD

**Issue by luocacy** [OpenBMB/AgentVerse#64]

**Comment by chenweize1998** [comment]
What do you mean by "Text Evaluation"? If you are looking for experiments on the benchmark data, you can refer to `Task-Solving CLI Example` in https://github.com/OpenBMB/AgentVerse#-getting-started

**Comment by luocacy** [comment]
It is the Demo of ChatEval, but it lacks the running command of this example. I'm more interested in this example.

**Comment by chenweize1998** [comment]
You should refer to https://github.com/thunlp/ChatEval.

**Comment by luocacy** [comment]
ok thanks
