### ISSUE TITLE
无效的令牌

### ISSUE THREAD

**Issue by LIUQI-creat** [OpenBMB/AgentVerse#69]
Hi
Thank you for the excellent work! 
I am using **release-0.1** for simulation. But I have encountered the following problem：
```
10/18/2023 21:42:49 - ERROR - root - 无效的令牌
10/18/2023 21:42:49 - WARNING - root - Retrying...
10/18/2023 21:42:54 - ERROR - root - Error communicating with OpenAI
10/18/2023 21:42:54 - WARNING - root - Retrying...
10/18/2023 21:42:56 - ERROR - root - 无效的令牌
10/18/2023 21:42:56 - WARNING - root - Retrying...
10/18/2023 21:42:56 - ERROR - root - Professor Michael failed to generate valid response.
```

**Comment by chenweize1998** [comment]
Can you take a try on the latest code? It should work fine in our latest code. For example, if you want to run the `nlp_classroom_9players` example, you can clone the latest code, and install it by using `python setup.py develop`, and then `python3 agentverse_command/main_simulation_cli.py --task simulation/nlp_classroom_9players `. More details can be found in https://github.com/OpenBMB/AgentVerse#simulation.

If you really want to use the `release-0.1`, you should:
1. If you are using Macos or Linux, you should make sure that the proxy of your terminal has been properly configured. This problem won't appear if your vpn is correctly setup. 
2. If you are using Windows, you can modify the code according to https://github.com/OpenBMB/AgentVerse/issues/45#issuecomment-1742455534.

**Comment by LIUQI-creat** [comment]
Thank you for your prompt reply! It's because I didn't fully set up the api.
