### ISSUE TITLE
求助：HTTP/1.1 502 Bad Gateway

### ISSUE THREAD

**Issue by JingsenZhang** [OpenBMB/AgentVerse#7]
05/23/2023 09:59:16 - INFO - httpx - HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 502 Bad Gateway"
05/23/2023 09:59:17 - INFO - httpx - HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 502 Bad Gateway"
05/23/2023 09:59:32 - INFO - httpx - HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 502 Bad Gateway"
05/23/2023 09:59:33 - INFO - httpx - HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 502 Bad Gateway"

**Comment by chenweize1998** [comment]
Seems that you are using tool. Did you start the local server in BMTools?
