### ISSUE TITLE
Failed to parse output of the model:

### ISSUE THREAD

**Issue by srcJin** [OpenBMB/AgentVerse#72]
Hi I had issue when running the example, both gui and cli:
Is there anything I can do to solve this issue?

will register airbnb
will register job_search
will register gradio_tools
will register travel
will register walmart
Failed to parse output of the model:Action: Speak
Action Input: Good morning, everyone! I hope you're all doing well today. For those who don't know me, my name is Professor Michael, and I'll be your instructor for today's lecture on the Transformer architecture of neural networks. Before we dive into the topic, I just want to remind you 
that if you have any questions, please feel free to raise 
your hand, and I'll be happy to address them. Now, let's get started!

**Comment by chenweize1998** [comment]
Hi! Can you pull the latest code and install again (uninstall agentverse and install it through `python setup.py develop`)? We should have fixed it in our latest code

**Comment by chenweize1998** [comment]
Closing this due to lack of feedback
