### ISSUE TITLE
 'Logger' object has no attribute 'warning'

### ISSUE THREAD

**Issue by HaSaKiYasuooo** [OpenBMB/AgentVerse#75]
文档内容似乎不一样了，文件没有main_demon.py
![image](https://github.com/OpenBMB/AgentVerse/assets/87591236/2dcea839-6846-4b63-a5cb-1d6d9def75ef)
而且我的启动模式是这个
![image](https://github.com/OpenBMB/AgentVerse/assets/87591236/5af6db81-c0f0-429e-a5d6-c9dcd0ee1118)

![image](https://github.com/OpenBMB/AgentVerse/assets/87591236/e74fdff2-b7fb-497a-bbea-5434fb5beeb2)

**Comment by chenweize1998** [comment]
我们近期更新比较频繁，中文文档还没来得及更新，你可以先参考一下英文的readme。logger的问题我们已经在最新的代码里修复了。你可以pull一下并且`python setup.py develop`安装一下（保险起见，先`pip uninstall agentverse`多次，直到提示找不到agentverse）。然后用下面的命令来运行
```bash
agentverse-simulation-gui --task simulation/nlp_classroom_9players
```
对于db_diag等case也是类似在这些task前面加上一个`simulation`，即`--task simulation/xxx`。
