### ISSUE TITLE
ValueError: reflection is not registered. Please register with the .register("reflection") method provided in AgentRegistry registry

### ISSUE THREAD

**Issue by serlina** [OpenBMB/AgentVerse#76]
When I want to run "main_simulation_cli.py  --task simulation/alice_home ", it reports error "raise ValueError(
ValueError: reflection is not registered. Please register with the .register("reflection") method provided in AgentRegistry registry"

How to fix this ,thank you

**Comment by chenweize1998** [comment]
Should be fixed in the latest code. Can you pull and try again?
