### ISSUE TITLE
 from_task() missing 1 required positional argument: 'tasks_dir'

### ISSUE THREAD

**Issue by HaSaKiYasuooo** [OpenBMB/AgentVerse#81]
运行宝可梦出现问题
![image](https://github.com/OpenBMB/AgentVerse/assets/87591236/1d4014a3-40c4-43a0-b5ad-e1de600245a1)

**Comment by chenweize1998** [comment]
宝可梦暂时请先使用https://github.com/OpenBMB/AgentVerse/tree/release-0.1 分支的代码，最新分支还未适配
