### ISSUE TITLE
simulation/db_diag执行错误，缺少其他任务模块

### ISSUE THREAD

**Issue by HaSaKiYasuooo** [OpenBMB/AgentVerse#83]
执行 agentverse-simulation-gui --task simulation/db_diag     出现错误
![image](https://github.com/OpenBMB/AgentVerse/assets/87591236/224e6311-0d48-47fe-863b-8cb41867d127)
![image](https://github.com/OpenBMB/AgentVerse/assets/87591236/4caeae25-242c-4620-b588-fd0a17b5b371)
而且对于其他模块
![image](https://github.com/OpenBMB/AgentVerse/assets/87591236/b523cd96-19fd-4370-8e34-1b1e31870494)
例如alice home,缺少环境参数
![image](https://github.com/OpenBMB/AgentVerse/assets/87591236/e54c642d-491b-4e9d-a101-6cfe03aeb065)

**Comment by chenweize1998** [comment]
gui只支持readme中提到的几个case。对于db_diag，你可能需要根据https://github.com/TsinghuaDatabaseGroup/DB-GPT进行相关配置

**Comment by chenweize1998** [comment]
如果有问题再重新打开issue

**Comment by gxy0410** [comment]
需要搭建[DB-GPT](https://github.com/TsinghuaDatabaseGroup/DB-GPT)才能够运行吗
