### ISSUE TITLE
release0.1宝可梦不能运行，missing 1 required positional argument: 'tasks_dir'

### ISSUE THREAD

**Issue by HaSaKiYasuooo** [OpenBMB/AgentVerse#84]
使用release0.1的分支，conda安装python3.9,安装BMtools
使用uvicorn pokemon_server:app --reload --port 10002    运行
显示BMtools没有安装，
 missing 1 required positional argument: 'tasks_dir'
![image](https://github.com/OpenBMB/AgentVerse/assets/87591236/cf90bc33-1d45-4bdc-8834-ffa51221b201)
![image](https://github.com/OpenBMB/AgentVerse/assets/87591236/81cd346d-c7df-4432-b291-0e6a22f06838)

**Comment by chenweize1998** [comment]
似乎不是release-0.1分支，请再确认一下。0.1分支中的pokemon_server代码不会是`Simulation.from_task`

**Comment by chenweize1998** [comment]
如果有问题再重新打开issue
