### ISSUE TITLE
www.127.0.0.1:7860无法打开

### ISSUE THREAD

**Issue by 779257747** [OpenBMB/AgentVerse#93]
在配置好了环境之后（使用了vpn），运行界面如下，但是并不能访问到127.0.0.1。请问下面的这个配置应该添加到哪个函数之中。
import os
os.environ["http_proxy"] = "http://127.0.0.1:7890"
os.environ["https_proxy"] = "http://127.0.0.1:7890"
os.environ["all_proxy"] = "socks5://127.0.0.1:7890"
<img width="856" alt="image" src="https://github.com/OpenBMB/AgentVerse/assets/63271390/8fbf30e3-cbf4-42e4-948c-638b950cd3b4">

**Comment by chenweize1998** [comment]
`agentverse-simulation`并不会在`127.0.0.1:7860`开启页面，您需要使用`agentverse-simulation-gui`。另外，如果`agentverse-simulation`长时间没有输出，请先确定您的命令行可以访问openai。在您的命令行里，能否正常运行如下程序？
```python3
import os
import openai
openai.api_key = os.getenv("OPENAI_API_KEY")

completion = openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "Hello!"}
  ]
)

print(completion.choices[0].message)

```

**Comment by 779257747** [comment]
> `agentverse-simulation`并不会在`127.0.0.1:7860`开启页面，您需要使用`agentverse-simulation-gui`。另外，如果`agentverse-simulation`长时间没有输出，请先确定您的命令行可以访问openai。在您的命令行里，能否正常运行如下程序？
> 
> ```python
> import os
> import openai
> openai.api_key = os.getenv("OPENAI_API_KEY")
> 
> completion = openai.ChatCompletion.create(
>   model="gpt-3.5-turbo",
>   messages=[
>     {"role": "system", "content": "You are a helpful assistant."},
>     {"role": "user", "content": "Hello!"}
>   ]
> )
> 
> print(completion.choices[0].message)
> ```

现在我可以看到127.0.0.1:7860的内容了但是我点了start autoplay之后没有动，在命令行里显示prompt end之后没有任何的action
![image](https://github.com/OpenBMB/AgentVerse/assets/63271390/9d16ee91-fea3-4710-a125-26f92e853ed8)

是我的openai没有配置对吗，我使用的是azure

**Comment by chenweize1998** [comment]
问题解决了吗？

**Comment by 779257747** [comment]
> 问题解决了吗？

解决了 谢谢您的帮助 感谢
