### ISSUE TITLE
main.py和main_demo.py文件在哪里？

### ISSUE THREAD

**Issue by caizhuoyue77** [OpenBMB/AgentVerse#98]
在git clone下来的文件夹中没有找到这个文件？

**Comment by chenweize1998** [comment]
我们前段时间更新了代码架构，请暂时先查看英文readme，我们最近将更新中文readme

**Comment by caizhuoyue77** [comment]
> 我们前段时间更新了代码架构，请暂时先查看英文readme，我们最近将更新中文readme

明白了，谢谢
