### ISSUE TITLE
自定义环境如何执行

### ISSUE THREAD

**Issue by 779257747** [OpenBMB/AgentVerse#99]
您好，我自定了一个自己的环境，写好了相关的config.yaml，接下来我使用命令agentverse-simulation --task medical/medical_consultation去执行，报错。接下来我认为应该是 agentverse-medical --task medical/medical_consultation命令来执行我新自定义的任务，我在阅读readme的时候，没有太明白怎么自定义解析器和将解析器定义在哪里，希望得到你的帮助，或者基于现在的最新版本代码，如何自定义自己的多智能体环境。
<img width="889" alt="image" src="https://github.com/OpenBMB/AgentVerse/assets/63271390/4e2749d6-8b6d-49e8-ae65-95ebedf8a824">

**Comment by 779257747** [comment]
./AgentVerse/agentverse/output_parser/output_parser.py
是应该在这个文件里来定义自定义环境下智能体的动作吗

**Comment by chenweize1998** [comment]
方便分享你的config文件吗？

**Comment by 779257747** [comment]
我的配置文件如下，我的任务类型是tasksolving类型，我的config.yaml是模仿着tasksolving/pythoncalculator写的，使用agentverse-tasksolving --task tasksolving/medical_consultation执行的现在运行的界面只显示loop0，没有输出
输出界面如下：
![image](https://github.com/OpenBMB/AgentVerse/assets/63271390/ceddd017-5155-44e5-9594-4a54b732a186)
配置文件如下：
cnt_agents: &cnt_agents 4
max_turn: &max_turn 3
max_inner_turns: &max_inner_turns 2
max_criticizing_rounds: 3

task_description: |-
  The patient experiences difficulty breathing, particularly when active or at night, and also reports a sensation of chest discomfort, sometimes accompanied by intense pain. They have a cough, occasionally with the production of phlegm. Over the past few months, the patient has lost approximately 10 kilograms in weight without any apparent reason. Additionally, the patient feels extreme fatigue, which is impacting their daily life.
  The aim of this conversation is to accurately conduct a medical consultation with a patient presenting with symptoms that may require diagnosis, management, inspect and possibly referral to a specialist.

prompts:
  role_assigner_prepend_prompt: &role_assigner_prepend_prompt |-

  role_assigner_append_prompt: &role_assigner_append_prompt |-
    You are the chief doctor leading a multidisciplinary team consultation. Given the patient's symptoms described below, you need to decide which specialists to consult for an accurate diagnosis and treatment plan:
    ${task_description}
    
    You can consult ${cnt_critic_agents} specialists from different fields. Which specialists will you consult to generate an accurate diagnosis?
    
    You should respond with a list of specialist descriptions. For example:
    1. a cardiologist specialized in heart diseases.
    2. a neurologist experienced in neurological disorders.
    3. an oncologist with expertise in cancer treatment.
    ...

    ${advice}
    You don't have to give the reason.

  solver_prepend_prompt: &solver_prepend_prompt |-
    You are faced with the task:
    ${task_description}

    Below is the chat history among you and other specialists.

  solver_append_prompt: &solver_append_prompt |-
    Using this information, can you provide a diagnosis and treatment recommendation? Explain your reasoning. Your response should contain only the diagnosis and treatment recommendation. Do not give any additional information.

  critic_prepend_prompt: &critic_prepend_prompt |-
    You are in a discussion group, aiming to reach a consensus on the diagnosis and treatment plan for the following case:
    ```
    ${task_description}
    ```

  
  critic_append_prompt: &critic_append_prompt |-
    Now the group is asking your opinion about it. Based on your knowledge
    in your field, do you agree that this solution can perfectly 
    solve the problem?
    Or do you have any ideas to improve it?
    
    - If you thinks it is perfect, use the following output format:
    Action: Agree
    Action Input: Agree.
    (Do not output your reason for agreeing!)

    - If you want to give complemented opinions to improve it or to contradict with it, use the following output format:
    Action: Disagree
    Action Input: (what you want to say in one line)
    
    P.S. Always remember you are ${role_description}!
    
    If no former solution or critic opinions are given, you can just disagree and output your idea freely, based on the expertise of your role.
    Remember, the ideas should be specific and detailed enough, not just general opinions.
    
    Please give your opinion

  evaluator_prepend_prompt: &evaluator_prepend_prompt |-

  evaluator_append_prompt: &evaluator_append_prompt |-
    You are a seasoned medical professional participating in a multi-specialist consultation. Your task is to critically evaluate the diagnosis and treatment suggestions provided by other medical experts. The recommendations are meant to ${task_description}. Your role is to ensure that the proposed medical opinions are accurate, thorough, and evidence-based.
  
    Please provide a rating (from 0 to 9) along with detailed feedback on how the diagnosis and treatment plan can be improved. In your evaluation, consider the following aspects:
  
    1. The medical rationale should be sound, with diagnoses and treatments backed by current medical standards and evidence.
    2. The proposed solution should comprehensively address the patient's condition and symptoms described in the task.
    3. The clarity of the medical advice, its accessibility to patients and other doctors, and whether it demonstrates a thorough understanding of the patient's needs.
    4. The suggestions should exhibit adaptability, offering alternative options where appropriate to accommodate varying patient responses or conditions.
  
    Please rate the medical recommendations in the following dimensions:
  
    1. Accuracy: Is the diagnosis accurate and based on sound medical knowledge and evidence?
    2. Comprehensiveness: Does the treatment plan address all aspects of the patient's condition and symptoms?
    3. Clarity: Is the medical advice presented clearly and understandably for all stakeholders?
    4. Adaptability: Are the recommendations flexible to cater to individual patient needs and potential variations in condition?
  
    In the fifth line of output, provide constructive criticism or advice for the presenting doctors to enhance the quality of future consultations.
  
    # Output format
    1. Accuracy: (a score between 0 and 9)
    2. Comprehensiveness: (a score between 0 and 9)
    3. Clarity: (a score between 0 and 9)
    4. Adaptability: (a score between 0 and 9)
    5. Advice: (your specific advice in one line)
  
    Here are the medical recommendations you have to evaluate:
    ${solution}
    

name: pipeline


environment:
  env_type: task-basic
  max_turn: *max_turn
  rule:
    role_assigner:
      type: role_description
      cnt_agents: *cnt_agents
    decision_maker:
      type: vertical-solver-first
      max_inner_turns: *max_inner_turns
    executor:
      type: none
    evaluator:
      type: basic

agents:
  - #role_assigner_agent:
    agent_type: role_assigner
    name: role assigner
    max_retry: 1000
    prepend_prompt_template: *role_assigner_prepend_prompt
    append_prompt_template: *role_assigner_append_prompt
    memory:
      memory_type: chat_history
    llm:
      llm_type: gpt-3.5-turbo
      model: "gpt-3.5-turbo"
      temperature: 0.7
      max_tokens: 256
    output_parser:
      type: role_assigner

  - #solver_agent:
    agent_type: solver
    name: Summarizer
    max_retry: 1000
    max_history: 5
    prepend_prompt_template: *solver_prepend_prompt
    append_prompt_template: *solver_append_prompt
    memory:
      memory_type: chat_history
    llm:
      llm_type: gpt-3.5-turbo
      model: "gpt-3.5-turbo"
      temperature: 0.7
      max_tokens: 2048
    output_parser:
      type: dummy

  - #critic_agents:
    agent_type: critic
    name: Reviewer
    max_retry: 1000
    max_history: 5
    role_description: |-
      Waiting to be assigned.
    prepend_prompt_template: *critic_prepend_prompt
    append_prompt_template: *critic_append_prompt
    memory:
      memory_type: chat_history
    llm:
      llm_type: gpt-3.5-turbo
      model: "gpt-3.5-turbo"
      temperature: 0.7
      max_tokens: 1024
    output_parser:
      type: critic

  - #executor_agent:
    agent_type: executor
    name: Dummy Executor
    max_retry: 1000
    memory:
      memory_type: chat_history
    llm:
      llm_type: gpt-3.5-turbo
      model: "gpt-3.5-turbo"
      temperature: 0.7
      max_tokens: 512
    output_parser:
      type: dummy

  - #evaluator_agent:
    agent_type: evaluator
    name: Evaluator
    max_retry: 1000
    role_description: |-
      Evaluator
    prepend_prompt_template: *evaluator_prepend_prompt
    append_prompt_template: *evaluator_append_prompt
    memory:
      memory_type: chat_history
    llm:
      llm_type: gpt-3.5-turbo
      model: "gpt-3.5-turbo"
      temperature: 0.7
      max_tokens: 1024
    output_parser:
      type: evaluator
      dimensions:
        - Accuracy
        - Comprehensiveness
        - Clarity
        - Adaptability

**Comment by 779257747** [comment]
还有一个小问题就是好像这个框架如果使用azure，现在不好使了。azure应该是有一些更新

**Comment by chenweize1998** [comment]
直接上传文件吧，文本粘贴在这里有些缩进看不出来

**Comment by 779257747** [comment]
> 直接上传文件吧，文本粘贴在这里有些缩进看不出来

上传不了config.yaml，我放在了飞书文档中可以看下：https://lawftech.feishu.cn/docx/TDS9dmSuTok1GAx0WyTcxrwInpf?from=from_copylink

现在的问题主要是azure的调用方式，我找了openai.py在response = openai.ChatCompletion.create(
                    messages=messages,
                    functions=functions,
                    **self.args.dict(),
                )中想要添加一个engine = "gpt-35-turbo"但是仍然没有成功。
                
昨天openai的服务器过载了现在已经可以运行起来了，只不过key受到了限制，并且azure的方式在框架中有些问题，现在azure的使用方式需要指定engine,azure的示例如下：
response = openai.Completion.create(
  engine="gpt-35-turbo",
  prompt="Classify the following news headline into 1 of the following categories: Business, Tech, Politics, Sport, Entertainment\n\nHeadline 1: Donna Steffensen Is Cooking Up a New Kind of Perfection. The Internet's most beloved cooking guru has a buzzy new book and a fresh new perspective\nCategory: Entertainment\n\nHeadline 2: Major Retailer Announces Plans to Close Over 100 Stores\nCategory:",
  temperature=0,
  max_tokens=60,
  top_p=1,
  frequency_penalty=0,
  presence_penalty=0,
  stop=None)

**Comment by chenweize1998** [comment]
config在我这里能正常跑起来，剩下的可能就是azure的问题了，但我们现在没有azure账号所以可能不太好debug。如果你在你的config中把所有agent的llm字段修改成以下形式
```yaml
llm:
      llm_type: gpt-3.5-turbo
      deployment_id: gpt-35-turbo
      temperature: 0.7
      max_tokens: 1024
```
然后把https://github.com/OpenBMB/AgentVerse/blob/d8825665c032295b51fa2b1d06d44e68b5453abd/agentverse/llms/openai.py#L47
的默认值改为default=None。再运行，看看这样是否可以

**Comment by 779257747** [comment]
> config在我这里能正常跑起来，剩下的可能就是azure的问题了，但我们现在没有azure账号所以可能不太好debug。如果你在你的config中把所有agent的llm字段修改成以下形式
> 
> ```yaml
> llm:
>       llm_type: gpt-3.5-turbo
>       deployment_id: gpt-35-turbo
>       temperature: 0.7
>       max_tokens: 1024
> ```
> 
> 然后把
> 
> https://github.com/OpenBMB/AgentVerse/blob/d8825665c032295b51fa2b1d06d44e68b5453abd/agentverse/llms/openai.py#L47
> 
> 
> 的默认值改为default=None。再运行，看看这样是否可以

已经好了，感谢您的帮助
